#version 450

layout (local_size_x = 16, local_size_y = 16) in;
//layout (binding = 0, rgba8) uniform readonly image2D inputImage;
//layout (binding = 1, rgba8) uniform image2D resultImage;

void main()
{	
	// Fetch neighbouring texels
	//vec3 rgb = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgb;

									
	//vec4 res = vec4(0.3 * rgb, 1.0);

	//imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), res);
}