#version 450

struct Light{
	vec4 position;
    vec4 color;
};

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0) uniform UBO
{
	mat4 model;
    mat4 view;
    mat4 proj;
} ubo;

layout (binding = 1, rgba8) uniform image2D positionMap;
layout (binding = 2, rgba8) uniform image2D normalMap;
layout (binding = 3, rgba8) uniform image2D colorMap;
layout (binding = 4, rgba8) uniform image2D uvMap;

layout (std140, binding = 5) buffer Lights
{
	Light lights[ ]; 
};

layout (binding = 6) uniform Config
{
	float intensity;
	float v1;
} config;

void main()
{
	vec4 fragColor = vec4(0.0);
	vec3 position = imageLoad(positionMap, ivec2(gl_GlobalInvocationID.xy)).rgb;
	if (position == vec3(0.0)) return;
	vec3 normal = imageLoad(normalMap, ivec2(gl_GlobalInvocationID.xy)).rgb;
	vec3 color = imageLoad(colorMap, ivec2(gl_GlobalInvocationID.xy)).rgb;
	vec2 uv = imageLoad(uvMap, ivec2(gl_GlobalInvocationID.xy)).xy;

	vec3 inPosition_w = (ubo.model * vec4(position, 1.0)).xyz; 
    vec3 inNormal_w = normalize(mat3(ubo.model) * normal);
    vec3 surfaceNormal = normalize(inNormal_w);
    vec3 cameraPos_w = -ubo.view[3].xyz;
    vec3 viewDirection = normalize(cameraPos_w - inPosition_w);

	vec3 rimLight = vec3(0.0);

	for (int i = 0; i < lights.length(); i++){
        Light light = lights[i];

		vec3 directionToLight = light.position.xyz - inPosition_w; // vector (Vertex World Position -> Light)
        float attenuation = 1.0 / dot(directionToLight, directionToLight); // 감쇠수치 = 거리 (같은거 dot production 하면 distance squared)
        directionToLight = normalize(directionToLight);

        float cosAngIncidence = max(dot(surfaceNormal, directionToLight), 0); // 노멀라이즈 된 두 벡터를 dot production 하면 각도가 같으면 1, 수직일때 0
        vec3 intensity = light.position.w * light.color.rgb * attenuation; // 거리에따라 감쇠 적용

		float rim  = 1 - clamp(dot(normalize(viewDirection), surfaceNormal), 0.0, 1.0);
		rim = rim * pow(rim, config.v1); 
		rimLight += rim * intensity; 
	}
	
	fragColor = vec4(color + config.intensity * rimLight, 1.0);
	imageStore(colorMap, ivec2(gl_GlobalInvocationID.xy), fragColor);
}